drop table session IF EXISTS;
create table session(
      id bigint GENERATED BY DEFAULT AS IDENTITY (start with 0, increment by 1) not null primary key,
      name varchar_ignorecase(50) not null,
      lastKnownLocation_id bigint,
      lastUpdated TIMESTAMP );
      
drop table session_location IF EXISTS;      
create table session_location (
		session_id bigint not null, 
		locations_id bigint not null,
		primary key(session_id,locations_id));      
      
drop table location IF EXISTS;
create table location(
      id bigint GENERATED BY DEFAULT AS IDENTITY (start with 0, increment by 1) not null primary key,
      latitude float not null,
      longitude float not null,
      trackedOn TIMESTAMP not null);
      
      

